# Default configuration for Auto Download Organizer

categories:
  Documents:
    - .pdf
    - .doc
    - .docx
    - .txt
    - .odt
    - .rtf
    - .tex
    - .wpd
  
  Images:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .svg
    - .webp
    - .ico
    - .tiff
  
  Videos:
    - .mp4
    - .avi
    - .mkv
    - .mov
    - .wmv
    - .flv
    - .webm
    - .m4v
  
  Audio:
    - .mp3
    - .wav
    - .flac
    - .aac
    - .ogg
    - .wma
    - .m4a
  
  Archives:
    - .zip
    - .rar
    - .7z
    - .tar
    - .gz
    - .bz2
    - .xz
  
  Programs:
    - .exe
    - .msi
    - .dmg
    - .pkg
    - .deb
    - .rpm
    - .appimage
  
  Code:
    - .py
    - .js
    - .html
    - .css
    - .java
    - .cpp
    - .c
    - .h
    - .json
    - .xml
  
  Spreadsheets:
    - .xlsx
    - .xls
    - .csv
    - .ods
  
  Presentations:
    - .pptx
    - .ppt
    - .odp
  
  Ebooks:
    - .epub
    - .mobi
    - .azw
    - .azw3

settings:
  create_date_folders: false
  log_file: organizer_log.json
  dry_run: false
